#!/bin/bash
# config/defaults.sh
# Default configuration. Sourced by lib/config.sh before strict user
# overrides from ~/.config/memory-pressure-monitor/config.sh.
#
# All keys are MPM_-prefixed and UPPER_SNAKE_CASE per CONSISTENCY.md.
# Override individual keys; do not edit this file in place.

# How often launchd invokes the sampler (seconds).
: "${MPM_INTERVAL_SECONDS:=30}"

# Cooldown before another red-zone notification fires (seconds).
: "${MPM_RED_COOLDOWN_SECONDS:=600}"

# Cooldown before another swap-in-use notification fires (seconds).
: "${MPM_SWAP_COOLDOWN_SECONDS:=900}"

# Swap usage threshold to consider "in use" (MiB).
: "${MPM_SWAP_THRESHOLD_MIB:=64}"

# Notification backend: "osascript" (default) or "terminal-notifier".
: "${MPM_NOTIFICATION_BACKEND:=osascript}"

# Optional system sound name (empty = silent).
: "${MPM_NOTIFICATION_SOUND:=}"

# Log file path.
: "${MPM_LOG_PATH:=$HOME/Library/Logs/memory-pressure-monitor.log}"
