#!/bin/bash
# config/defaults.sh
# Default configuration. Sourced by lib/config.sh before strict user
# overrides from ~/.config/memory-pressure-monitor/config.sh.
#
# All keys are MPM_-prefixed and UPPER_SNAKE_CASE per CONSISTENCY.md.
# Override individual keys; do not edit this file in place.

# How often launchd invokes the sampler (seconds).
: "${MPM_INTERVAL_SECONDS:=30}"

# Cooldown before another red-zone notification fires (seconds).
: "${MPM_RED_COOLDOWN_SECONDS:=600}"

# Whether warn-zone notifications fire (1 = on, 0 = off).
: "${MPM_WARN_ALERTS_ENABLED:=1}"

# Cooldown before another warn-zone notification fires (seconds).
: "${MPM_WARN_COOLDOWN_SECONDS:=1800}"

# Cooldown before another swap-in-use notification fires (seconds).
: "${MPM_SWAP_COOLDOWN_SECONDS:=900}"

# Swap usage threshold to consider "in use" (MiB).
: "${MPM_SWAP_THRESHOLD_MIB:=64}"

# Re-fire a swap notification when current swap exceeds the last-alerted
# level by this many MiB. Default 1 GiB.
: "${MPM_SWAP_GROWTH_MIB:=1024}"

# Notification backend: "popup" (default — centered window via the
# dashboard app), "osascript" (banner), "terminal-notifier", or "stderr"
# (test). The popup backend falls back to osascript if the app bundle is
# missing.
: "${MPM_NOTIFICATION_BACKEND:=popup}"

# Optional system sound name (empty = silent).
: "${MPM_NOTIFICATION_SOUND:=}"

# Log file path.
: "${MPM_LOG_PATH:=$HOME/Library/Logs/memory-pressure-monitor.log}"
